app/accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts.views import UserRegView
from accounts.views import ActivatedView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registration/', UserRegView.as_view(), name="registration-link"),
    path('activated/<uuid:username>', ActivatedView.as_view(), name='activated-link'),
]

app/customers/urls.py
from django.urls import path
from customers.views import CustomerListView
from customers.views import CustomerDetalesView
from customers.views import CustomerCreateView
from customers.views import CustomerUpdateView
from customers.views import CustomerDeleteView

urlpatterns = [
    path('customer-list/', CustomerListView.as_view(), name="customer-list-link"),
    path('customer-details/<int:pk>', CustomerDetalesView.as_view(), name='customer-details-link'),
    path('customer-create/', CustomerCreateView.as_view(), name="customer-create-link"),
    path('customer-update/<int:pk>', CustomerUpdateView.as_view(), name='customer-update-link'),
    path('customer-delete/<int:pk>', CustomerDeleteView.as_view(), name="customer-delete-link"),
]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from customers.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name="home-link"),
    path('', include('customers.urls')),
    path("accounts/", include("accounts.urls")),
    path('auth/', include('django.contrib.auth.urls')),
]

app/accounts/models.py
import uuid

from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    email = models.EmailField("email address", blank=True, unique=True)
    username = models.CharField('username', max_length=150, unique=True, default=str(uuid.uuid4()))

app/customers/models.py
from django.db import models

class Customer(models.Model):
    name = models.CharField(max_length=35)
    age = models.PositiveSmallIntegerField(max_length=3)
    city = models.CharField(max_length=20)
    create = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(max_length=40)
    business = models.BooleanField()

app/accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import RedirectView
from accounts.models import User
from accounts.RegForm import UserFormForCreate


class UserRegView(CreateView):
    model = User
    form_class = UserFormForCreate
    success_url = reverse_lazy("home-link")
    template_name = 'registration.html'

    # def form_valid(self, form):
    #     from django.contrib import messages
    #     messages.info(self.request,"Thanks for reg!")
    #     return super().form_valid(form)


class ActivatedView(RedirectView):
    pattern_name="home-link"


    def get_redirect_url(self, *args, **kwargs):
        username = kwargs.pop("username")
        user = get_object_or_404(User,usename=username,is_active=False)
        user.is_active=True
        user.save(update_filds=("is_active",))

        user.refresh_from_db()
        return super().get_redirect_url(*args,**kwargs)

app/customers/views.py
from customers.models import Customer
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.views.generic import DetailView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.urls import reverse_lazy
from customers.CustomerForm import CustomerFormForCreate

class CustomerListView(ListView):
    model = Customer
    template_name = 'customerList.html'

class CustomerDetalesView(DetailView):
    model = Customer
    template_name = 'customerDetails.html'

class CustomerCreateView(CreateView):
    model = Customer
    form_class = CustomerFormForCreate
    success_url = reverse_lazy("customer-list-link")
    template_name = 'customerCreate.html'

class CustomerUpdateView(UpdateView):
    model = Customer
    form_class = CustomerFormForCreate
    success_url = reverse_lazy("customer-list-link")
    template_name = 'customerUpdate.html'

class CustomerDeleteView(DeleteView):
    model = Customer
    success_url = reverse_lazy("customer-list-link")
    template_name = 'customerDelete.html'

class Home(TemplateView):
    template_name = 'index.html'

app/accounts/templates/registration.html
{% extends 'base.html' %}

{% block main_content %}

<form method="post" >
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

app/customers/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MyWebSite</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <header class="d-flex justify-content-center py-3">
      <ul class="nav nav-pills">
        <li class="nav-item"><a href="{% url 'home-link' %}" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="{% url 'customer-list-link' %}" class="nav-link">Customer List</a></li>
        <li class="nav-item"><a href="{% url 'customer-create-link' %}" class="nav-link">Add Customer</a></li>
          <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Account</a>
        <ul class="dropdown-menu">
            {% if not request.user.is_authenticated%}
            <li class="dropdown-item"><a href="{% url 'login' %}">Login</a></li>
            <li class="dropdown-item"><a href="{% url 'registration-link' %}"  >Reg</a></li>
            {% else %}
            <li class="dropdown-item" ><a href="#">MyPage</a></li>
            <li class="dropdown-item"><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
        </ul>
      </li>





      </ul>


    </header>









{% block main_content%}

{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/customers/templates/customerCreate.html
{% extends 'base.html' %}

{% block main_content %}
{% if not request.user.is_authenticated%}
You don't have permission!
<form method="post" >
    {% csrf_token %}
    {{ form }}
    <button type="button" class="btn btn-primary">Submit</button>
</form>
{% else %}
<form method="post" >
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endif %}
{% endblock %}

app/customers/templates/customerDelete.html
{% extends 'base.html' %}

{% block main_content %}
{% if not request.user.is_authenticated%}
You don't have permission!
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="button" class="btn btn-primary">yes</button>
</form>
<button type="submit" class="btn btn-primary"><a href="#" >no</a></button>
{% else %}
Are you sure?
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-primary">yes</button>
</form>
<button type="submit" class="btn btn-primary"><a href="{% url 'customer-list-link' %}" >no</a></button>
{% endif %}
{% endblock %}

app/customers/templates/customerDetails.html
{% extends 'base.html' %}

{% block main_content %}
<ul class="list-group">
    <li class="list-group-item active">Customer Details:</li>
    <li class="list-group-item">id: {{object.id}}</li>
    <li class="list-group-item">name: {{object.name}}</li>
    <li class="list-group-item">age: {{object.age}}</li>
    <li class="list-group-item">city: {{object.city}}</li>
    <li class="list-group-item">create: {{object.create}}</li>
    <li class="list-group-item">email: {{object.email}}</li>
    <li class="list-group-item">business: {{object.business}}</li>
</ul>
{% endblock %}

app/customers/templates/customerList.html
{% extends 'base.html' %}

{% block main_content%}

<table class="table table-dark">
    <tr>
        <th>ID</th>
        <th>name</th>
        <th>age</th>
        <th>city</th>
        <th>create</th>
        <th>Email</th>
        <th>business</th>
        <th>Details</th>
        <th>Update</th>
        <th>Delete</th>
    </tr>
    {%for i in customer_list%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.name}}</td>
        <td>{{i.age}}</td>
        <td>{{i.city}}</td>
        <td>{{i.create}}</td>
        <td>{{i.email}}</td>
        <td>{{i.business}}</td>
        <td><a href="{% url 'customer-details-link' pk=i.pk %}">Details</a></td>
        <td><a href="{% url 'customer-update-link' pk=i.pk %}">Update</a></td>
        <td><a href="{% url 'customer-delete-link' pk=i.pk %}">Delete</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

app/customers/templates/customerUpdate.html
{% extends 'base.html' %}

{% block main_content %}
{% if not request.user.is_authenticated%}
You don't have permission!
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="button" class="btn btn-primary">Submit</button>
</form>
{% else %}
<form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endif %}
{% endblock %}

app/customers/templates/index.html
{% extends 'base.html' %}

{% block main_content %}
hi
{% endblock %}